### ISSUE TITLE
0.1.2 TODO

### ISSUE THREAD

**Issue by sirjonasxx** [sirjonasxx/G-Python#1]
- [x] async intercept methods
- [x] i64/long support in hpacket
- [x] look into cpu usage
